# Generated by Django 3.2.9 on 2021-11-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_receita', models.ImageField(blank=True, default='0', null=True, upload_to='fotos/%d/%m/%Y')),
            ],
        ),
    ]
